/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.PecasEletricas;
import Model.PecasMecanica;
import Model.Pecas;
import controller.Control_Pecas;
import java.util.ArrayList;
import javax.swing.JTextPane;
import principal.Main;


/**
 *
 * @author Bruno
 */
public class inserir_pecas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(inserir_pecas.class.getName());
    private ArrayList<Pecas> listaP = new ArrayList<>();
    private javax.swing.JDesktopPane desktop;
    /**
     * Creates new form inserir_os
     */
    public inserir_pecas() {
        
        
       
        initComponents();
  
        tela_conf.setVisible(false);
        this.lab_volt.setVisible(false);
        this.lab_material.setVisible(false);
        this.jScrollPane4.setVisible(false);
        this.jScrollPane5.setVisible(false);
        
      
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela_conf = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        bot_confSim = new javax.swing.JButton();
        bol_confNao = new javax.swing.JButton();
        popupMenu1 = new java.awt.PopupMenu();
        label_principal = new javax.swing.JLabel();
        bot_sair = new javax.swing.JButton();
        lab_nome = new javax.swing.JLabel();
        lab_quantidade = new javax.swing.JLabel();
        lab_quantidade1 = new javax.swing.JLabel();
        checkMec = new javax.swing.JCheckBox();
        checkEle = new javax.swing.JCheckBox();
        bot_cadastrar = new javax.swing.JButton();
        lista = new javax.swing.JComboBox<>();
        lab_material = new javax.swing.JLabel();
        lab_volt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        var_nome = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        var_valor = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        var_quantidade = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        var_material = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        var_voltagem = new javax.swing.JTextPane();

        tela_conf.setVisible(true);

        jLabel1.setText("DESEJA REALIZAR ESTES REGISTROS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setInheritsPopupMenu(false);
        jLabel1.setName(""); // NOI18N

        bot_confSim.setText("SIM");
        bot_confSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_confSimActionPerformed(evt);
            }
        });

        bol_confNao.setText("NÃO");
        bol_confNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bol_confNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tela_confLayout = new javax.swing.GroupLayout(tela_conf.getContentPane());
        tela_conf.getContentPane().setLayout(tela_confLayout);
        tela_confLayout.setHorizontalGroup(
            tela_confLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela_confLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(bot_confSim, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bol_confNao, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tela_confLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        tela_confLayout.setVerticalGroup(
            tela_confLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela_confLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(tela_confLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot_confSim, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bol_confNao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 47, Short.MAX_VALUE))
        );

        popupMenu1.setLabel("popupMenu1");
        popupMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupMenu1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_principal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_principal.setText("CADASTRO DE PEÇAS ");

        bot_sair.setText("VOLTAR");
        bot_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_sairActionPerformed(evt);
            }
        });

        lab_nome.setText("NOME:");

        lab_quantidade.setText("QUANTIDADE:");

        lab_quantidade1.setText("VALOR:");

        checkMec.setText("MECANICA");
        checkMec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMecActionPerformed(evt);
            }
        });

        checkEle.setText("ELETRICA");
        checkEle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEleActionPerformed(evt);
            }
        });

        bot_cadastrar.setText("CADASTRAR");
        bot_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cadastrarActionPerformed(evt);
            }
        });

        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UNID", "PC", "KG" }));
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });

        lab_material.setText("MATERIAL:");

        lab_volt.setText("VOLTAGEM");

        jScrollPane1.setViewportView(var_nome);

        jScrollPane2.setViewportView(var_valor);

        jScrollPane3.setViewportView(var_quantidade);

        jScrollPane4.setViewportView(var_material);

        jScrollPane5.setViewportView(var_voltagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lab_quantidade1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                    .addComponent(lab_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lab_material, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lab_volt, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jScrollPane5))
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lab_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(1, 1, 1)
                                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(checkMec, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(checkEle, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(bot_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bot_sair)))
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkEle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkMec, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab_nome)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab_quantidade1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lab_quantidade))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab_material)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab_volt)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot_sair)
                    .addComponent(bot_cadastrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_sairActionPerformed
        tela_inserir tela_inserir = new tela_inserir();
        tela_inserir.setVisible(true);
        this.dispose();        

    }//GEN-LAST:event_bot_sairActionPerformed

    private void checkMecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMecActionPerformed
        if (checkMec.isSelected()) {
            checkEle.setSelected(false);
        this.lab_volt.setVisible(false);
        this.lab_material.setVisible(true);
        this.jScrollPane4.setVisible(true);
        this.jScrollPane5.setVisible(false);
        } if (!checkMec.isSelected()) {
        this.lab_material.setVisible(false);
        this.jScrollPane4.setVisible(false);
        }
    }//GEN-LAST:event_checkMecActionPerformed

    private void checkEleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEleActionPerformed
        if (checkEle.isSelected()) {
            checkMec.setSelected(false);
             
        this.lab_volt.setVisible(true);
        this.lab_material.setVisible(false);
        this.jScrollPane4.setVisible(false);
        this.jScrollPane5.setVisible(true);
        }if (!checkEle.isSelected()) {
        this.jScrollPane5.setVisible(false);
        this.lab_volt.setVisible(false);
        }
    }//GEN-LAST:event_checkEleActionPerformed

    private void bot_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cadastrarActionPerformed
        Control_Pecas cont_pecas = new Control_Pecas();
        String nomePeca = var_nome.getText();
        float valorPecas = Float.parseFloat(var_valor.getText());
        
       String unid = (String) lista.getSelectedItem();
               
        int quant_Pecas = Integer.parseInt(var_quantidade.getText());
        float valor_unid = (valorPecas/quant_Pecas);
        
        if(checkMec.isSelected()){
            
          String tipo_elemento = "MECANICO";
          String carac_elemento=var_material.getText();
          PecasMecanica pecMec=new PecasMecanica(nomePeca, valor_unid,unid, quant_Pecas, valor_unid, tipo_elemento,carac_elemento);
          listaP.add(pecMec);
          
        }else if(checkEle.isSelected()){
            
            String tipo_elemento = "Eletrico";
            String carac_elemento=var_voltagem.getText();
            PecasEletricas pecEle = new PecasEletricas(nomePeca, valor_unid,unid, quant_Pecas, valor_unid, tipo_elemento,carac_elemento);
            
            listaP.add(pecEle);
        }
        cont_pecas.cadastrarPecas(listaP);
        Main.clean(new JTextPane[]{var_nome,var_valor,var_quantidade,var_material,var_voltagem});   
        listaP.clear();
    }//GEN-LAST:event_bot_cadastrarActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed

     
    }//GEN-LAST:event_listaActionPerformed

    private void bot_confSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_confSimActionPerformed
       Control_Pecas cont_pecas = new Control_Pecas();
        cont_pecas.cadastrarPecas(listaP);
        tela_inserir tela_inserir = new tela_inserir();
        tela_inserir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_confSimActionPerformed

    private void bol_confNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bol_confNaoActionPerformed
        tela_inserir tela_inserir = new tela_inserir();
        tela_inserir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bol_confNaoActionPerformed

    private void popupMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupMenu1ActionPerformed
    
    }//GEN-LAST:event_popupMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new inserir_pecas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bol_confNao;
    private javax.swing.JButton bot_cadastrar;
    private javax.swing.JButton bot_confSim;
    private javax.swing.JButton bot_sair;
    private javax.swing.JCheckBox checkEle;
    private javax.swing.JCheckBox checkMec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lab_material;
    private javax.swing.JLabel lab_nome;
    private javax.swing.JLabel lab_quantidade;
    private javax.swing.JLabel lab_quantidade1;
    private javax.swing.JLabel lab_volt;
    private javax.swing.JLabel label_principal;
    public javax.swing.JComboBox<String> lista;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JInternalFrame tela_conf;
    public javax.swing.JTextPane var_material;
    public javax.swing.JTextPane var_nome;
    public javax.swing.JTextPane var_quantidade;
    public javax.swing.JTextPane var_valor;
    public javax.swing.JTextPane var_voltagem;
    // End of variables declaration//GEN-END:variables
}
