/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import reports.RelatoriosUsu;   
import controller.Control_Ordem_De_Serico;
import Model.Ordem_De_Servico;
import javax.swing.JTextPane;
import principal.Main;
        

/**
 *
 * @author Bruno
 */
public class inserir_os extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(inserir_os.class.getName());
  
    /**
     * Creates new form inserir_os
     */
    public inserir_os() {
      
        initComponents();
   
      
    }
public int extrairID(String texto) {
    try {
        texto = texto.replace("ID:", "").trim();
        String numero = texto.split("\\|")[0].trim();
        return Integer.parseInt(numero);
    } catch (Exception e) {
        return -1;
    }
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela_conf = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        bot_confSim = new javax.swing.JButton();
        bol_confNao = new javax.swing.JButton();
        popupMenu1 = new java.awt.PopupMenu();
        jSpinner1 = new javax.swing.JSpinner();
        label_principal = new javax.swing.JLabel();
        bot_sair = new javax.swing.JButton();
        lab_Clien = new javax.swing.JLabel();
        lab_Func = new javax.swing.JLabel();
        list_clien = new javax.swing.JComboBox<>();
        list_func = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        var_obeserv = new javax.swing.JTextPane();
        lab_observa = new javax.swing.JLabel();
        bot_cadastro = new javax.swing.JButton();

        tela_conf.setVisible(true);

        jLabel1.setText("DESEJA REALIZAR ESTES REGISTROS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setInheritsPopupMenu(false);
        jLabel1.setName(""); // NOI18N

        bot_confSim.setText("SIM");
        bot_confSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_confSimActionPerformed(evt);
            }
        });

        bol_confNao.setText("NÃO");
        bol_confNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bol_confNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tela_confLayout = new javax.swing.GroupLayout(tela_conf.getContentPane());
        tela_conf.getContentPane().setLayout(tela_confLayout);
        tela_confLayout.setHorizontalGroup(
            tela_confLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela_confLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(bot_confSim, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bol_confNao, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tela_confLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        tela_confLayout.setVerticalGroup(
            tela_confLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela_confLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(tela_confLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot_confSim, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bol_confNao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 47, Short.MAX_VALUE))
        );

        popupMenu1.setLabel("popupMenu1");
        popupMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupMenu1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_principal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_principal.setText("CADASTRO DE O.S");

        bot_sair.setText("VOLTAR");
        bot_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bot_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_sairActionPerformed(evt);
            }
        });

        lab_Clien.setText("CLIENTE");

        lab_Func.setText("FUNCIONARIO");

        RelatoriosUsu relat1 = new RelatoriosUsu();
        list_clien.setModel(new javax.swing.DefaultComboBoxModel<>(relat1.vw_Cliente()));

        RelatoriosUsu relat = new RelatoriosUsu();
        list_func.setModel(new javax.swing.DefaultComboBoxModel<>(relat.vw_Funcionario()));

        jScrollPane1.setViewportView(var_obeserv);

        lab_observa.setText("DESCRIÇÃO :");

        bot_cadastro.setText("CADASTRO");
        bot_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bot_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lab_observa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lab_Clien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_Func, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(list_func, 0, 215, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(list_clien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(bot_sair)))
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_Func)
                    .addComponent(list_func, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_Clien)
                    .addComponent(list_clien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lab_observa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot_sair)
                    .addComponent(bot_cadastro))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_sairActionPerformed
        
        tela_inserir tela_inserir = new tela_inserir();
        tela_inserir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_sairActionPerformed

    private void bot_confSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_confSimActionPerformed
 
        tela_inserir tela_inserir = new tela_inserir();
        tela_inserir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_confSimActionPerformed

    private void bol_confNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bol_confNaoActionPerformed
        tela_inserir tela_inserir = new tela_inserir();
        tela_inserir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bol_confNaoActionPerformed

    private void popupMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupMenu1ActionPerformed
    
    }//GEN-LAST:event_popupMenu1ActionPerformed

    private void bot_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cadastroActionPerformed
        Control_Ordem_De_Serico cont_os =new Control_Ordem_De_Serico();
       int func = extrairID(list_func.getSelectedItem().toString());
        int clien = extrairID(list_clien.getSelectedItem().toString());
        String obs = var_obeserv.getText();
        
        if(func!= -1 || clien !=-1){
       Ordem_De_Servico os = new Ordem_De_Servico(func,clien,obs);
       cont_os.criaOS(os);
        }else{
            System.out.println("ERRO...");
        }
        
       Main.clean(new JTextPane[]{ var_obeserv });
        
    }//GEN-LAST:event_bot_cadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new inserir_os().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bol_confNao;
    private javax.swing.JButton bot_cadastro;
    private javax.swing.JButton bot_confSim;
    private javax.swing.JButton bot_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lab_Clien;
    private javax.swing.JLabel lab_Func;
    private javax.swing.JLabel lab_observa;
    private javax.swing.JLabel label_principal;
    private javax.swing.JComboBox<String> list_clien;
    private javax.swing.JComboBox<String> list_func;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JInternalFrame tela_conf;
    private javax.swing.JTextPane var_obeserv;
    // End of variables declaration//GEN-END:variables
}
