/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.Cliente;
import Model.Funcionario;
import controller.Control_Usuario;
import javax.swing.JTextPane;
import principal.Main;

public class inserir_usuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(inserir_usuario.class.getName());

    /**
     * Creates new form inserir_usuario
     */
    public inserir_usuario() {
        initComponents();
          this.lab_salario.setVisible(false);
          this.varsalario.setVisible(false);
          this.label_secundaria.setVisible(false);
          this.lab_ano.setVisible(false);
          this.var_ano.setVisible(false);
          this.lab_modelo.setVisible(false);
          this.varmodelo.setVisible(false);
          this.lab_placa.setVisible(false);
          this.varplaca.setVisible(false);
          
          
                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        label_principal = new javax.swing.JLabel();
        lab_nome = new javax.swing.JLabel();
        var_nome = new javax.swing.JScrollPane();
        valnome = new javax.swing.JTextPane();
        lab_cpf = new javax.swing.JLabel();
        var_cpf = new javax.swing.JScrollPane();
        valcpf = new javax.swing.JTextPane();
        lab_telefone = new javax.swing.JLabel();
        var_telefone = new javax.swing.JScrollPane();
        valtel = new javax.swing.JTextPane();
        bot_sair = new javax.swing.JButton();
        bot_cadastrar = new javax.swing.JButton();
        checkCliente = new javax.swing.JCheckBox();
        checkFuncionario = new javax.swing.JCheckBox();
        lab_salario = new javax.swing.JLabel();
        varsalario = new javax.swing.JScrollPane();
        valsalario = new javax.swing.JTextPane();
        lab_ano = new javax.swing.JLabel();
        var_ano = new javax.swing.JScrollPane();
        valano = new javax.swing.JTextPane();
        lab_modelo = new javax.swing.JLabel();
        varmodelo = new javax.swing.JScrollPane();
        valmodelo = new javax.swing.JTextPane();
        lab_placa = new javax.swing.JLabel();
        varplaca = new javax.swing.JScrollPane();
        valplaca = new javax.swing.JTextPane();
        label_secundaria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_principal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_principal.setText("CADASTRO DE USUARIO ");

        lab_nome.setText("NOME:");

        var_nome.setViewportView(valnome);

        lab_cpf.setText("CPF:");

        var_cpf.setViewportView(valcpf);

        lab_telefone.setText("TEL:");

        var_telefone.setViewportView(valtel);

        bot_sair.setText("VOLTAR");
        bot_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_sairActionPerformed(evt);
            }
        });

        bot_cadastrar.setText("CADASTRAR");
        bot_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cadastrarActionPerformed(evt);
            }
        });

        checkCliente.setText("CLIENTE");
        checkCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkClienteActionPerformed(evt);
            }
        });

        checkFuncionario.setText("FUNCIONARIO");
        checkFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFuncionarioActionPerformed(evt);
            }
        });

        lab_salario.setText("SALARIO");
        lab_salario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lab_salarioAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        varsalario.setViewportView(valsalario);

        lab_ano.setText("ANO:");

        var_ano.setViewportView(valano);

        lab_modelo.setText("MODELO: ");

        varmodelo.setViewportView(valmodelo);

        lab_placa.setText("PLACA:");

        varplaca.setViewportView(valplaca);

        label_secundaria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_secundaria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_secundaria.setText("CADASTRO DO AUTOMOVEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bot_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(147, 147, 147))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(varsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91)))
                                .addComponent(bot_sair)
                                .addGap(0, 27, Short.MAX_VALUE))
                            .addComponent(label_secundaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(checkCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkFuncionario)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lab_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(varmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lab_cpf)
                            .addGap(18, 18, 18)
                            .addComponent(var_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lab_telefone)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(var_telefone))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lab_nome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(var_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lab_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lab_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(var_ano)
                            .addGap(206, 206, 206)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lab_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(label_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkFuncionario)
                    .addComponent(checkCliente))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(var_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(var_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(var_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_secundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab_salario)
                    .addComponent(varsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lab_ano)
                    .addComponent(var_ano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_placa)
                    .addComponent(varplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(varmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot_sair)
                    .addComponent(bot_cadastrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_sairActionPerformed
        tela_inserir tela_inserir = new tela_inserir();
        tela_inserir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_sairActionPerformed

    private void bot_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cadastrarActionPerformed
        String nome = valnome.getText();
        String cpf = valcpf.getText();
        String telefone = valtel.getText();
        
        if (checkCliente.isSelected()) {
            Control_Usuario cont_usu=new Control_Usuario();
            String tipo="CLIENTE";
            String moto_modelo=valmodelo.getText();
            int moto_ano = Integer.parseInt(valano.getText());
            String moto_placa=valplaca.getText();
            
            Cliente cliente = new Cliente(nome, cpf, telefone, tipo, moto_modelo, moto_ano, moto_placa);   
            cont_usu.cadastro(cliente);
            
        }else if(checkFuncionario.isSelected()){
            Control_Usuario cont_usu=new Control_Usuario();
            String tipo="FUNCIONARIO";
            float salario = Float.parseFloat(valsalario.getText());
            Funcionario funcionario = new Funcionario(nome,cpf,telefone,tipo,salario);
            cont_usu.cadastro(funcionario);	 
        }

        Main.clean(new JTextPane[]{ valnome,valcpf,valtel,valmodelo,valano,valplaca,valsalario});
    }//GEN-LAST:event_bot_cadastrarActionPerformed

    private void checkClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkClienteActionPerformed
           
        if (checkCliente.isSelected()) {
            checkFuncionario.setSelected(false);           
            
          this.label_secundaria.setVisible(true);
          this.lab_ano.setVisible(true);
          this.var_ano.setVisible(true);
          this.lab_modelo.setVisible(true);
          this.varmodelo.setVisible(true);
          this.lab_placa.setVisible(true);
          this.varplaca.setVisible(true);
            
           } if (!checkCliente.isSelected()) {
                       
            this.lab_salario.setVisible(false);
            this.varsalario.setVisible(false);

            this.label_secundaria.setVisible(false);
            this.lab_ano.setVisible(false);
            this.var_ano.setVisible(false);
            this.lab_modelo.setVisible(false);
            this.varmodelo.setVisible(false);
            this.lab_placa.setVisible(false);
            this.varplaca.setVisible(false);
    }
    }//GEN-LAST:event_checkClienteActionPerformed

    private void checkFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFuncionarioActionPerformed
        if (checkFuncionario.isSelected()) {
            checkCliente.setSelected(false);           
            this.lab_salario.setVisible(true);
            this.varsalario.setVisible(true);
        }   if (!checkFuncionario.isSelected()) {   
            this.lab_salario.setVisible(false);
            this.varsalario.setVisible(false);
}
    }//GEN-LAST:event_checkFuncionarioActionPerformed

    private void lab_salarioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lab_salarioAncestorAdded
       
    }//GEN-LAST:event_lab_salarioAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new inserir_usuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cadastrar;
    private javax.swing.JButton bot_sair;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox checkCliente;
    private javax.swing.JCheckBox checkFuncionario;
    private javax.swing.JLabel lab_ano;
    public javax.swing.JLabel lab_cpf;
    private javax.swing.JLabel lab_modelo;
    private javax.swing.JLabel lab_nome;
    private javax.swing.JLabel lab_placa;
    private javax.swing.JLabel lab_salario;
    private javax.swing.JLabel lab_telefone;
    private javax.swing.JLabel label_principal;
    private javax.swing.JLabel label_secundaria;
    private javax.swing.JTextPane valano;
    public javax.swing.JTextPane valcpf;
    private javax.swing.JTextPane valmodelo;
    private javax.swing.JTextPane valnome;
    private javax.swing.JTextPane valplaca;
    private javax.swing.JTextPane valsalario;
    private javax.swing.JTextPane valtel;
    private javax.swing.JScrollPane var_ano;
    public javax.swing.JScrollPane var_cpf;
    private javax.swing.JScrollPane var_nome;
    public javax.swing.JScrollPane var_telefone;
    private javax.swing.JScrollPane varmodelo;
    private javax.swing.JScrollPane varplaca;
    private javax.swing.JScrollPane varsalario;
    // End of variables declaration//GEN-END:variables
}   
