/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
/**
 *
 * @author Bruno
 */
public class tela_main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tela_main.class.getName());

    /**
     * Creates new form tela_main
     */
    public tela_main() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bot_inserir = new javax.swing.JButton();
        bot_atualizar = new javax.swing.JButton();
        bot_remover = new javax.swing.JButton();
        label_principal = new javax.swing.JLabel();
        bot_sair1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bot_info = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        bot_inserir.setText("INSERIR");
        bot_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_inserirActionPerformed(evt);
            }
        });

        bot_atualizar.setText("ATUALIZAR");
        bot_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_atualizarActionPerformed(evt);
            }
        });

        bot_remover.setText("REMOVER");
        bot_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_removerActionPerformed(evt);
            }
        });

        label_principal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_principal.setText("SISTEMA GENRENCIADOR DE MANUTENÇÃO");

        bot_sair1.setText("SAIR");
        bot_sair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_sair1ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        bot_info.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bot_info.setLabel("!");
        bot_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_infoActionPerformed(evt);
            }
        });

        jButton2.setText("FINALIZADO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(bot_sair1)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addComponent(bot_info, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bot_inserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bot_remover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bot_atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bot_info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(bot_inserir)
                .addGap(18, 18, 18)
                .addComponent(bot_remover)
                .addGap(18, 18, 18)
                .addComponent(bot_atualizar)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bot_sair1)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_atualizarActionPerformed
        tela_atualizar tela_atu = new tela_atualizar();
        tela_atu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_atualizarActionPerformed

    private void bot_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_inserirActionPerformed
        tela_inserir tela_ins=new tela_inserir();
        tela_ins.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_inserirActionPerformed

    private void bot_sair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_sair1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bot_sair1ActionPerformed

    private void bot_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_infoActionPerformed
        
        new sobre().setVisible(true); 
        
        
    }//GEN-LAST:event_bot_infoActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        
    }//GEN-LAST:event_formComponentAdded

    private void bot_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_removerActionPerformed
        tela_remove tela_re = new tela_remove();
        tela_re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_removerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tela_finalização tela_fin = new tela_finalização();
        tela_fin.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new tela_main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_atualizar;
    private javax.swing.JButton bot_info;
    private javax.swing.JButton bot_inserir;
    private javax.swing.JButton bot_remover;
    private javax.swing.JButton bot_sair1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel label_principal;
    // End of variables declaration//GEN-END:variables
}
