/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import reports.RelatoriosUsu;
import reports.RelatoriosPecas;
import reports.RelatoriosOs;
import controller.Control_Ordem_De_Serico;
import controller.Control_Pecas;
import controller.Control_Usuario;
import principal.Main;

        
/**
 *
 * @author Bruno
 */
public class tela_remove extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tela_remove.class.getName());

    /**
     * Creates new form tela_remove
     */
    public tela_remove() {
        initComponents();
        
        this.lab_os.setVisible(false);
        this.list_os.setVisible(false);
        this.lab_pecas.setVisible(false);
        this.list_pecas.setVisible(false);
        this.lab_usuario.setVisible(false);
        this.list_usuarios.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_principal = new javax.swing.JLabel();
        lab_pecas = new javax.swing.JLabel();
        lab_usuario = new javax.swing.JLabel();
        list_pecas = new javax.swing.JComboBox<>();
        list_usuarios = new javax.swing.JComboBox<>();
        lab_os = new javax.swing.JLabel();
        list_os = new javax.swing.JComboBox<>();
        lab_secundaria = new javax.swing.JLabel();
        boxUsuario = new javax.swing.JCheckBox();
        boxOs = new javax.swing.JCheckBox();
        boxPecas = new javax.swing.JCheckBox();
        bot_voltar = new javax.swing.JButton();
        bot_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_principal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_principal.setText("REMOVER");

        lab_pecas.setText("PEÇAS");

        lab_usuario.setText("USUARIO");

        RelatoriosPecas relat1 = new RelatoriosPecas();
        list_pecas.setModel(new javax.swing.DefaultComboBoxModel<>(relat1.relat_PecasSimp()));

        RelatoriosUsu relat = new RelatoriosUsu();
        list_usuarios.setModel(new javax.swing.DefaultComboBoxModel<>(relat.vw_usuarios()));

        lab_os.setText("O.S");

        RelatoriosOs relat2 = new RelatoriosOs();
        list_os.setModel(new javax.swing.DefaultComboBoxModel<>(relat2.relat_OsSimp()));

        lab_secundaria.setText("Marque a opção que deseja remover");

        boxUsuario.setText("USUARIO");
        boxUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxUsuarioActionPerformed(evt);
            }
        });

        boxOs.setText("O.S");
        boxOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxOsActionPerformed(evt);
            }
        });

        boxPecas.setText("PEÇAS");
        boxPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPecasActionPerformed(evt);
            }
        });

        bot_voltar.setText("VOLTAR");
        bot_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_voltarActionPerformed(evt);
            }
        });

        bot_cadastrar.setText("REMOVER");
        bot_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lab_secundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lab_os, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(list_os, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lab_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lab_pecas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(list_usuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(list_pecas, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(71, 71, 71))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boxPecas)
                        .addGap(96, 96, 96)
                        .addComponent(boxOs)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bot_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(196, 196, 196)
                        .addComponent(bot_voltar)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab_secundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxUsuario)
                    .addComponent(boxOs)
                    .addComponent(boxPecas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_usuario)
                    .addComponent(list_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_pecas)
                    .addComponent(list_pecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_os)
                    .addComponent(list_os, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bot_voltar)
                    .addComponent(bot_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cadastrarActionPerformed
       
        if(this.boxUsuario.isSelected()){
           RelatoriosUsu relat = new RelatoriosUsu();
           Control_Usuario contUsu = new Control_Usuario();
           int usu = Main.extrairID(list_usuarios.getSelectedItem().toString());
           contUsu.remover(usu);
           list_usuarios.setModel(new javax.swing.DefaultComboBoxModel<>(relat.vw_usuarios()));         
            
        }
         if(this.boxPecas.isSelected()){  
          RelatoriosPecas relat1 = new RelatoriosPecas();
          Control_Pecas contPecas = new Control_Pecas();
          int pec = Main.extrairID(list_pecas.getSelectedItem().toString());
          System.out.println(pec);
          contPecas.removerPecas(pec);          
          list_pecas.setModel(new javax.swing.DefaultComboBoxModel<>(relat1.relat_PecasSimp()));   
             
        }
        if(this.boxOs.isSelected()){ 
         RelatoriosOs relat2 = new RelatoriosOs();
        Control_Ordem_De_Serico contOs = new Control_Ordem_De_Serico();
        int os = Main.extrairID(list_os.getSelectedItem().toString());       
        contOs.removeOS(os);      
        list_os.setModel(new javax.swing.DefaultComboBoxModel<>(relat2.relat_OsSimp()));
    
        }     
    }//GEN-LAST:event_bot_cadastrarActionPerformed

    private void bot_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_voltarActionPerformed
        
        tela_main tela_main= new tela_main();
        tela_main.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_bot_voltarActionPerformed

    private void boxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxUsuarioActionPerformed
        if(this.boxUsuario.isSelected()){
        this.lab_usuario.setVisible(true);
        this.list_usuarios.setVisible(true);
        
    }//GEN-LAST:event_boxUsuarioActionPerformed
   if(!this.boxUsuario.isSelected()){
        this.lab_usuario.setVisible(false);
        this.list_usuarios.setVisible(false);
        
    } 
}
    private void boxPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPecasActionPerformed
       if(this.boxPecas.isSelected()){     
        this.lab_pecas.setVisible(true);
        this.list_pecas.setVisible(true);
        }
        if(!this.boxPecas.isSelected()){     
        this.lab_pecas.setVisible(false);
        this.list_pecas.setVisible(false);
        }
    }//GEN-LAST:event_boxPecasActionPerformed

    private void boxOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxOsActionPerformed
      if(this.boxOs.isSelected()){
        this.lab_os.setVisible(true);
        this.list_os.setVisible(true);    
    }  
      if(!this.boxOs.isSelected()){
        this.lab_os.setVisible(false);
        this.list_os.setVisible(false);    
    }   
      
    }//GEN-LAST:event_boxOsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new tela_remove().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cadastrar;
    private javax.swing.JButton bot_voltar;
    private javax.swing.JCheckBox boxOs;
    private javax.swing.JCheckBox boxPecas;
    private javax.swing.JCheckBox boxUsuario;
    private javax.swing.JLabel lab_os;
    private javax.swing.JLabel lab_pecas;
    private javax.swing.JLabel lab_secundaria;
    private javax.swing.JLabel lab_usuario;
    private javax.swing.JLabel label_principal;
    private javax.swing.JComboBox<String> list_os;
    private javax.swing.JComboBox<String> list_pecas;
    private javax.swing.JComboBox<String> list_usuarios;
    // End of variables declaration//GEN-END:variables
}
