/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Bruno
 */
public class tela_inserir extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tela_inserir.class.getName());

    /**
     * Creates new form tela_inserir
     */
    public tela_inserir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bot_relatorios = new javax.swing.JButton();
        bot_inserir = new javax.swing.JButton();
        bot_atualizar = new javax.swing.JButton();
        bot_sair = new javax.swing.JButton();
        bot_remover = new javax.swing.JButton();
        label_principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bot_relatorios.setText("CADASTRO DE USUARIOS");
        bot_relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_relatoriosActionPerformed(evt);
            }
        });

        bot_inserir.setText("CADASTRO DE O.S");
        bot_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_inserirActionPerformed(evt);
            }
        });

        bot_atualizar.setText("INSUMOS POR O.S");
        bot_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_atualizarActionPerformed(evt);
            }
        });

        bot_sair.setText("VOLTAR");
        bot_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_sairActionPerformed(evt);
            }
        });

        bot_remover.setText("CADASTRO DE PEÇA");
        bot_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_removerActionPerformed(evt);
            }
        });

        label_principal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_principal.setText("CADASTRO ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bot_sair)
                .addGap(25, 25, 25))
            .addComponent(label_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bot_relatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bot_inserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bot_remover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bot_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(label_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(bot_relatorios)
                .addGap(18, 18, 18)
                .addComponent(bot_inserir)
                .addGap(18, 18, 18)
                .addComponent(bot_remover)
                .addGap(18, 18, 18)
                .addComponent(bot_atualizar)
                .addGap(24, 24, 24)
                .addComponent(bot_sair)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_relatoriosActionPerformed
        new inserir_usuario().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_bot_relatoriosActionPerformed

    private void bot_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_inserirActionPerformed
        inserir_os tela_os=new inserir_os();
        tela_os.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_inserirActionPerformed

    private void bot_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_atualizarActionPerformed
       inserir_peca_os pc = new inserir_peca_os();
        pc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_atualizarActionPerformed

    private void bot_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_sairActionPerformed
        tela_main main = new tela_main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_sairActionPerformed

    private void bot_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_removerActionPerformed
        
        inserir_pecas ins_pecas = new inserir_pecas();
        ins_pecas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_removerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new tela_inserir().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_atualizar;
    private javax.swing.JButton bot_inserir;
    private javax.swing.JButton bot_relatorios;
    private javax.swing.JButton bot_remover;
    private javax.swing.JButton bot_sair;
    private javax.swing.JLabel label_principal;
    // End of variables declaration//GEN-END:variables
}
